### ISSUE TITLE
Switch back to Fabric

### ISSUE THREAD

**Issue by Nekkok** [DragonEggBedrockBreaking/VanillaDisable#11]
I'm very sad...

**Comment by DragonEggBedrockBreaking** [comment]
What’s the problem with Quilt? Most fabric mods should work without changes on Quilt.

**Comment by kxkxrxtx** [comment]
The thing is that's not loading in my game. If i can provide you any log to demonstrate it, tell me which one you need.

**Comment by ViciousBadger** [comment]
Many other mods definitely do not work with Quilt at the moment.. it would be wonderful to use this mod with Fabric, I hate villages with a passion and I have yet to find any reliable way to get rid of them along with mansions and outposts. How difficult would it be to make this mod work with fabric?

**Comment by DragonEggBedrockBreaking** [comment]
I have decided to use 1.19.x as a quilt testing ground. Since for gamerules, Quilt offers basically nothing, from Minecraft 1.20, this mod will likely be back on fabric,

**Comment by ViciousBadger** [comment]
I see. Version 20 is due some time in 2023, so I guess I must take the matters into my own hands.. the villagers shall perish one way or another..

**Comment by DragonEggBedrockBreaking** [comment]
Now that 1.19.3 has been announced, imma just get it released for that. I just assumed that 1.19.2 will be the final 1.19.x update before 1.20 when writing the original comment.

**Comment by DragonEggBedrockBreaking** [comment]
The development branch has been switched to Fabric. If you know how to, you can either compile it yourself or get a build from github actions. Otherwise, wait until 1.19.3.

Note that the development branch also has a pretty major feature - the gamerule command has been rewritten. Documentation for this will only be released when 2.3.0 is released, so if you choos to use it now, you will have to figure out how to use it. (Autocomplete exists, so should be easy).

**Comment by DragonEggBedrockBreaking** [comment]
Done.
