### ISSUE TITLE
VanillaDisable GetDifficulty Crash

### ISSUE THREAD

**Issue by bloodheaven-dev** [DragonEggBedrockBreaking/VanillaDisable#24]
I looked through this crashlog, it seems that the getDifficulty function seems to be at fault here.

Is there a mixin to disable it, maybe it conflicts with one of my mods.
Crash happened randomly, came back after being afk and Minecraft was closed.

[crash-2024-09-25_18.50.51-server.txt](https://github.com/user-attachments/files/17135331/crash-2024-09-25_18.50.51-server.txt)

**Comment by DragonEggBedrockBreaking** [comment]
Thank you for the report. I think this is a fundamental issue with my mod which I have noticed before but is hard to reproduce. I will try to address this in an update soon.

**Comment by DragonEggBedrockBreaking** [comment]
I have a potential fix that could help, however this issue is very difficult to reproduce so it's hard to know if the issue has been fixed. If you have any more crash reports please send them here. Through this bug, I also discovered a different piston-related crash bug which will also be fixed in the new release.

**Comment by DragonEggBedrockBreaking** [comment]
Try v4.0.2
