### ISSUE TITLE
[1.21.1] [neo] option to disable log stripping?

### ISSUE THREAD

**Issue by Cixon** [DragonEggBedrockBreaking/VanillaDisable#25]
i dont see it on this mod... am i misunderstanding something?

**Comment by DragonEggBedrockBreaking** [comment]
In theory, this can be done with `/vd rule item matches '%_axe' other works false`. However, that feature is currently broken. It has been fixed in commit https://github.com/DragonEggBedrockBreaking/VanillaDisable/commit/c8aea5205473e2601d0fea13e6d3c873d82efebc, and this fix will be in a future release. I will close this issue once that is released. You can download the latest beta [here](https://github.com/DragonEggBedrockBreaking/VanillaDisable/actions/runs/11197332461/artifacts/2019832899) (you need to be logged in for this to work).

**Comment by DragonEggBedrockBreaking** [comment]
Fixed in 4.0.3 (download on Modrinth for [Fabric/Quilt](https://modrinth.com/mod/vanilla-disable/version/4.0.3) or [Neoforge](https://modrinth.com/mod/vanilla-disable/version/XhE0Pm1L)).

Use `/vd rule item matches '%_axe' other works false`.
